# Generated by Django 3.2.8 on 2021-10-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
