# Generated by Django 3.2.8 on 2021-10-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0002_remove_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
