# Generated by Django 3.2.8 on 2021-10-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0003_alter_consultas_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='horarios',
            field=models.CharField(help_text='HH:MM (Se houver mais de um horário, separar por vírgula)', max_length=100),
        ),
    ]
